


#Test message
GET localhost:3000


# Product API
### Create a new product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Zara Shoes",
  "price": 100,
  "description": "Zara Shoes",
  "image": "https://www.zara.com/uk/en/leather-ankle-boots-p171002p5072505.html",
  "brand": "Zara",
  "stock": 5
}


### Get all products
GET http://localhost:3000/products?limit=10&offset=0


### Get a product by ID
GET http://localhost:3000/products/1


### Update product by ID
PATCH http://localhost:3000/products/2
Content-Type: application/json

{
  "price": 201
}

### Delete product by ID
DELETE localhost:3000/products/2


#Category API
### Create a new category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "Shoes",
  "description": "Shoes",
  "color": "#000000"
}

### Get all categories
GET http://localhost:3000/categories?limit=10&offset=0

### Get a category by ID
GET http://localhost:3000/categories/1

### Update category by ID
PATCH http://localhost:3000/categories/1
Content-Type: application/json

{
  "name": "Shoes"
}

### Delete category by ID
DELETE localhost:3000/categories/1


#Brand API
### Create a new brand
POST http://localhost:3000/brands
Content-Type: application/json

{
  "name": "Zara",
  "description": "Zara",
  "image": "https://www.zara.com/uk/en/leather-ankle-boots-p171002p5072505.html"
}

### Get all brands
GET http://localhost:3000/brands?limit=10&offset=0

### Get a brand by ID

GET http://localhost:3000/brands/1

### Update brand by ID
PATCH http://localhost:3000/brands/1
Content-Type: application/json

{
  "name": "Zara Shoes"
}

### Delete brand by ID
DELETE localhost:3000/brands/1




# User API
### Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "yeimar112003@gmail.com",
  "password": "123456",
  "role": "admin"
}

### Get all users
GET http://localhost:3000/users?limit=10&offset=0

### Get a user by ID
GET http://localhost:3000/users/1

### Update user by ID
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "John David"
}

### Delete user by ID
DELETE localhost:3000/users/1


### Get all products by user ID

GET http://localhost:3000/users/1/orders




